apiVersion: v1
kind: Service
metadata:
  name: sbdocker-service
spec:
  selector:
    app: sbdocker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  clusterIP: 
  type: LoadBalancer

